create table public.project_task_step_extension_requests(
 id uuid primary key default gen_random_uuid(), task_step_id uuid not null references public.project_task_steps(id) on delete restrict,
 current_due_at timestamptz not null, requested_due_at timestamptz not null, reason text not null check(length(trim(reason))>=5),
 status text not null default 'pending' check(status in ('pending','approved','rejected')), requested_by uuid not null references public.profiles(id) on delete restrict,
 reviewed_by uuid references public.profiles(id) on delete restrict, review_notes text, reviewed_at timestamptz, created_at timestamptz not null default now(), check(requested_due_at>current_due_at)
);
create table public.project_task_step_attention_notices(
 id uuid primary key default gen_random_uuid(), task_step_id uuid not null references public.project_task_steps(id) on delete restrict,
 target_user_id uuid not null references public.profiles(id) on delete restrict, due_at timestamptz not null, reason text not null,
 status text not null default 'pending' check(status in ('pending','active','rejected','acknowledged')), reviewed_by uuid references public.profiles(id) on delete restrict,
 reviewed_at timestamptz,rejection_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(task_step_id,due_at)
);
alter table public.project_task_step_extension_requests enable row level security;
alter table public.project_task_step_attention_notices enable row level security;
revoke all on public.project_task_step_extension_requests,public.project_task_step_attention_notices from anon,authenticated;
grant select on public.project_task_step_extension_requests,public.project_task_step_attention_notices to authenticated;
create policy task_step_extensions_read on public.project_task_step_extension_requests for select to authenticated using(exists(select 1 from public.project_task_steps step where step.id=project_task_step_extension_requests.task_step_id));
create policy task_step_attention_read on public.project_task_step_attention_notices for select to authenticated using(exists(select 1 from public.project_task_steps step where step.id=project_task_step_attention_notices.task_step_id));

create or replace function public.request_project_task_step_extension(p_step_id uuid,p_requested_due_at timestamptz,p_reason text)
returns uuid language plpgsql security definer set search_path='' as $$ declare actor_id uuid:=(select auth.uid()); item public.project_task_steps; result_id uuid; begin select * into item from public.project_task_steps where id=p_step_id and status in('open','returned'); if not found or item.assigned_to<>actor_id then raise exception 'Only the assignee can request an extension'; end if; if p_requested_due_at<=item.due_at or length(trim(coalesce(p_reason,'')))<5 then raise exception 'Invalid extension request'; end if; insert into public.project_task_step_extension_requests(task_step_id,current_due_at,requested_due_at,reason,requested_by) values(item.id,item.due_at,p_requested_due_at,trim(p_reason),actor_id) returning id into result_id; return result_id; end $$;
create or replace function public.review_project_task_step_extension(p_extension_id uuid,p_decision text,p_notes text default null)
returns uuid language plpgsql security definer set search_path='' as $$ declare actor_id uuid:=(select auth.uid()); item public.project_task_step_extension_requests; begin if actor_id is null or not private.has_permission('tasks.manage_threads') then raise exception 'The current user cannot review extensions'; end if; select * into item from public.project_task_step_extension_requests where id=p_extension_id and status='pending' for update; if not found or p_decision not in('approved','rejected') then raise exception 'Extension is unavailable'; end if; update public.project_task_step_extension_requests set status=p_decision,reviewed_by=actor_id,review_notes=nullif(trim(coalesce(p_notes,'')),''),reviewed_at=now() where id=item.id; if p_decision='approved' then update public.project_task_steps set due_at=item.requested_due_at,updated_at=now() where id=item.task_step_id; end if; insert into public.notifications(recipient_id,notification_type,title,body,data) values(item.requested_by,'project_task_extension_'||p_decision,case when p_decision='approved' then 'تم اعتماد تمديد المهمة' else 'تم رفض تمديد المهمة' end,coalesce(nullif(trim(coalesce(p_notes,'')),''),'راجع صندوق المهمة.'),jsonb_build_object('task_step_id',item.task_step_id,'category','operational')); return item.id; end $$;
create or replace function public.generate_project_task_step_attention_notices() returns integer language plpgsql security definer set search_path='' as $$ declare inserted_count integer; begin insert into public.project_task_step_attention_notices(task_step_id,target_user_id,due_at,reason) select step.id,step.assigned_to,step.due_at,'تجاوزت المهمة موعدها دون رد أو تمديد معتمد.' from public.project_task_steps step join public.project_task_threads thread on thread.id=step.task_thread_id join public.projects project on project.id=thread.project_id where step.status in('open','returned') and step.due_at<now() and project.health_status<>'yellow' on conflict(task_step_id,due_at) do nothing; get diagnostics inserted_count=row_count; return inserted_count; end $$;
create or replace function public.review_project_task_step_attention_notice(p_notice_id uuid,p_decision text,p_reason text default null) returns uuid language plpgsql security definer set search_path='' as $$ declare actor_id uuid:=(select auth.uid()); item public.project_task_step_attention_notices; begin if actor_id is null or not private.has_permission('tasks.manage_threads') then raise exception 'The current user cannot review notices'; end if; select * into item from public.project_task_step_attention_notices where id=p_notice_id and status='pending' for update; if not found or p_decision not in('active','rejected') then raise exception 'Notice is unavailable'; end if; if p_decision='rejected' and length(trim(coalesce(p_reason,'')))<3 then raise exception 'Rejection reason is required'; end if; update public.project_task_step_attention_notices set status=p_decision,reviewed_by=actor_id,reviewed_at=now(),rejection_reason=case when p_decision='rejected' then trim(p_reason) end,updated_at=now() where id=item.id; insert into public.notifications(recipient_id,notification_type,title,body,data) values(item.target_user_id,'project_task_attention_'||p_decision,case when p_decision='active' then 'لفت نظر قائم' else 'تم رفض لفت النظر' end,coalesce(nullif(trim(coalesce(p_reason,'')),''),item.reason),jsonb_build_object('task_step_id',item.task_step_id,'notice_id',item.id,'category','attention')); return item.id; end $$;
create trigger audit_task_step_extensions after insert or update on public.project_task_step_extension_requests for each row execute function private.audit_row_change();
create trigger audit_task_step_attention after insert or update on public.project_task_step_attention_notices for each row execute function private.audit_row_change();
revoke all on function public.request_project_task_step_extension(uuid,timestamptz,text) from public,anon; grant execute on function public.request_project_task_step_extension(uuid,timestamptz,text) to authenticated;
revoke all on function public.review_project_task_step_extension(uuid,text,text) from public,anon; grant execute on function public.review_project_task_step_extension(uuid,text,text) to authenticated;
revoke all on function public.generate_project_task_step_attention_notices() from public,anon,authenticated; grant execute on function public.generate_project_task_step_attention_notices() to service_role;
revoke all on function public.review_project_task_step_attention_notice(uuid,text,text) from public,anon; grant execute on function public.review_project_task_step_attention_notice(uuid,text,text) to authenticated;
do $$ begin if exists(select 1 from pg_extension where extname='pg_cron') then perform cron.unschedule(jobid) from cron.job where jobname='generate-project-task-attention-notices'; perform cron.schedule('generate-project-task-attention-notices','*/5 * * * *','select public.generate_project_task_step_attention_notices()'); end if; exception when undefined_table or invalid_schema_name then null; end $$;
